server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:******
    username: root
    password: ******


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lpjworkroom.new_buddyoj_backend.model
